### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by haerts** [scilus/fibernavigator#216]
Dear all,

I would like to interactively explore resting-state functional connectivity. I preprocessed my data using SPM12, in which I registered the T1 data to fMRI space. 
When I try to open my coregistered T1 data in fibernavigator, I always get the error "Segmentation fault (core dumped)". 
Am I doing something wrong? 

Thanks!

Best,
Hannelore

**Comment by chamberm** [comment]
Hi Hannelore,


Could you look what datatype is your t1? Ideally it should be int16 (short).
Float32 will also work fine.

Best,
Maxime

(Also, you dont need to downsample your t1 to fmri-space to perform rt-fmri. In fact, I highly suggest keeping it in its original space.)

**Comment by haerts** [comment]
Hi Maxime,
My T1s are signed 16 bit integer (little endian)...
Thanks for the tip, I'll coregister without reslicing, see if it might help!  
Best, 
Hannelore

**Comment by haerts** [comment]
Hi Maxime,
I can now open my T1 in the fibernavigator, but when I try to load the fMRI results (4mm isotropic), I get the error that the dimensions of the loaded files must be the same. Would you then recommend to upsample the fMRI data to T1 space? 
Thanks!

**Comment by haerts** [comment]
I'm sorry, I didn't see the fMRI tab. Now I got it!
Thanks anyway!

**Comment by chamberm** [comment]
You may want to have a look at this page:

http://chamberm.github.io/fMRItutorials.html

Let us know if you need any support.
Maxime

**Comment by haerts** [comment]
Hi Maxime,

Thank you for your quick reply. I now have my data in the fibernavigator. I adjusted the strides to +1,+2,+3,+4 (as in the demo data) but I noticed that something goes wrong in the registration of fMRI to T1 (Iattached a screenshot from fibernavigator). However, I checked the registration in MRtrix, FSLview and MRIcron, and there it seems to be fine. Could it be that the fibernavigator cannot read transformation matrices in image headers?

![fibernavigator_registration](https://cloud.githubusercontent.com/assets/10127659/19893364/37f141fa-a049-11e6-8ee4-f10ca8431434.png)

Best,
Hannelore

**Comment by chamberm** [comment]
Hi,

If you wish to send me your t1 & rs-fmri, I could have a look to see what's the problem. Mostly It's just a matter of slice ordering  or x-y flip in the fibernavigator. Other point to consider once this is sorted out: your rs-fmri data also needs to be demean (the way z-scores are implemented for visualization, once again).

here is my email adress: maxime.chamberland@usherbrooke.ca if you wish to dropbox both .nii files.

Best,
Maxime

**Comment by haerts** [comment]
I put the data in a dropbox folder and shared it with you. I tried flipping the axes but without success so far... With demeaned, do you then mean that I should do global signal regression?
Thank you for your help!

**Comment by chamberm** [comment]
Got the data. Did a quick test even if its misaligned and works good (see the dmn etc. So, Forget about what I said for demeaning ;).  

I'll try to see how we can now realign those, maybe it simply has to do with the fact that your t1 is anisotrop (1x1.3x1)

Come back to you in a bit

**Comment by chamberm** [comment]
from the quick tests I've run: seems like it is related to the orientation (LPI-RPI). I'll have to dig in the fibernav, but I know we've changed to way files are loaded about a year ago. In any case, I've reproduced the issue in mrview by changing the t1 from LPI to RPI:

![screenshot from 2016-11-01 16 16 18](https://cloud.githubusercontent.com/assets/3778285/19897323/fff4ef1a-a02d-11e6-9702-d851d4477c7c.png)

in the fibernav, using the unchanged files: same problem (minut the flip X). But, rs-networks looks good.
![screenshot from 2016-11-01 16 19 33](https://cloud.githubusercontent.com/assets/3778285/19897324/fffb6386-a02d-11e6-93f3-39608c5bf729.png)

Maybe you can try to think of a workaround by directly altering your data spaces ? I'll investigate more later on my side.

Best,
Maxime

**Comment by haerts** [comment]
Hi Maxime,

I reoriented my resting-state fMRI to neurological, both T1 and fMRI are now in neurological convention. However, this doesn't seem to solve the problem...
![fibernavigator_registration_neurological](https://cloud.githubusercontent.com/assets/10127659/19962804/a401df32-a1b9-11e6-9795-ac2d67c7d250.png)

I'll put the new fMRI images in the dropbox folder, in case you have some time to have a look.
Thank you in advance!

Best,
Hannelore

**Comment by chamberm** [comment]
Adding @jchoude to the loop. With your permission, I'll share with him the data.

**Comment by haerts** [comment]
Of course, no problem!

**Comment by haerts** [comment]
Hi Maxime,
Did you already have a chance to look at the error?
I tried it with another dataset (acquired at another institution, different scanner) but the problem remains the same, despite the strides being the same for T1 and fMRI...
Thanks!

**Comment by jchoude** [comment]
Hi Hannelore,

just a quick message to tell you that we are looking at the issue. As suspected, the affine is not really used in the Fibernavigator. This is why you ware getting this kind of behavior.

We'll try to send you a fix in the coming days.

**Comment by haerts** [comment]
Hi,
Any news on the fix of the affine transforms in the Fibernavigator?
Thanks!

**Comment by chamberm** [comment]
Hi Hannelore,
sorry for the late reply. I think @jchoude was still investigating the issue.

It has to do with a rotation matrix that is not taken into account. We we'll get back to you if a workaround can be found.
Max

**Comment by jchoude** [comment]
Hi @haerts 

sorry for the gigagntic delay in replying.

So, as was pointed out before by @chamberm , the affine matrices of datasets are not really used internally. This is a shortcoming of the Fibernavigator, and, without going in all historical details, is inherited from the old code that we built the current functionalities on top.

Supporting the affine information would be the correct way to do this, as you experienced in many other tools. However, our resources are very limited to work on this. Anyway, this kind of work would almost be better suited for starting a completely new project.

With all that said, @chamberm and I took the whole day yesterday to test various "hacks" for your data. None of them was satisfactory. That being known, one thing we could suggest would be to

1. Set the transform of your original T1 dataset to identity (you can keep the translation part, just no rotation).
2. Register your fmri dataset to this updated T1. Final affine will probably have no rotation, and some translation.

Then, it *should* work.

We also saw that @chamberm datasets were correctly working because the acquisition "box" (in the scanner console) was not rotated or moved for the fMRI sequence, only resized. When compared to your dataset, that's not the case. If at all possible, it might be easier to get this working if your next acquisitions try to do the same.

Once again, sorry for the delay and shortcomings.

As a sidenote, some partners are currently working on a new tool (unreleased yet) where we hope to add RT-fMRI, and where everything is correctly aligned in world space. If you agree, I can add you to our list of interested users, and write to you when we have a viable beta working. Would you be interested?

**Comment by haerts** [comment]
Hi @jchoude and @chamberm 

Thank you for all your effort and advice. I'll give it a try!
And you can definitely add me to the interested users for the new tool!

Best,
Hannelore
