### ISSUE TITLE
How to determine when to use the flip?

### ISSUE THREAD

**Issue by jiangjiane** [scilus/fibernavigator#224]
Where can I find the documentation of the FiberNavigator?

**Comment by chamberm** [comment]
Hi Jiang,

Thanks for reaching out. If you want more info about the tool, I invite you to watch some of these videos, as we don't "per se" have full documentation of the tool.

Maybe start here:
https://github.com/scilus/fibernavigator/wiki/Tutorials

Particularly, the new Real-time tractography video:
https://www.youtube.com/watch?v=A3KCekqPTok&t=1s
and

Basics of the tool (bit outdated, but still good):
https://www.youtube.com/watch?v=8X_eOB9zYU8&hd=1&hl=en

Could you also describe a bit more into detail the problem encountered? Do you mean FLIP regarding datasets or glyph flips e.g. peaks within a voxel ?

Thanks,
Maxime

**Comment by jiangjiane** [comment]
Hi Maxime,
Thanks for your detail answers.
My question is  that I don't know when to use the flip. For example, when I load a VOI data, I don't know if it is matching with the wholeBrain data.

Thanks,
Jiang

**Comment by chamberm** [comment]
Hi Jiang,

It's a bit tricky since it depends on how your VOI was created. Was it using the fibernav? From the top on my head I'd say you dont need to flip anything if it has the same orientation (e.g. LPI, RPI..) as your wholeBrain (here wholeBrain you mean anatomy like a T1, or more like whole-brain tracts?)

I'd check what makes sense with regards to an underlying anatomical scan basically. Could be also that if it was saved with the fibernavigator, some flipX occurs during loading, it's something I have seen in the past.

Best,
Maxime

**Comment by jiangjiane** [comment]
Hi Maxime,
My whole Brain means anatomy like a T1. When I generated a CC (as a VOI) and saved with the fibernavigator, some flipY occured during reloading CC. I am confused for it.

Thanks,
Jiang

**Comment by chamberm** [comment]
Hi Jiang,

yes I see what you mean. It is a known issue, that i've encountered before. Easy to fix, I'll try to push something in my version once a new release comes out. (I'd suggest pulling code and downloading the tool from here: https://github.com/chamberm/fibernavigator)

In the meantime, simply flipping the mask when opening it is the way to go, and then, re-saving it on the disk should do the trick.

Best,
Maxime

**Comment by jiangjiane** [comment]
Hi Maxime,
Thank you very much for your answer.
The FiberNavigator is very useful to me.

Thanks,
Jiang
