### ISSUE TITLE
installation of fibernavigator on ubuntu 20.04

### ISSUE THREAD

**Issue by christophenioche** [scilus/fibernavigator#231]
Dear Colleague,

During the make the gtk2 library is not known.
Indeed on ubuntu 20.04 gtk2 is obsolete and only gtk3 exists.

What can we do to fix it ?

see below:
fibernavigator/build$ make
[  1%] Linking CXX executable bin/fibernavigator
/usr/bin/ld : not found -lwx_gtk2u_gl-3.0
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/fibernavigator.dir/build.make:1150 : bin/fibernavigator] Erreur 1
make[1]: *** [CMakeFiles/Makefile2:76 : CMakeFiles/fibernavigator.dir/all] Erreur 2
make: *** [Makefile:84 : all] Erreur 2

**Comment by ANG13** [comment]
I was able to compile by installing libwxgtk3.0-gtk3-dev package, and change CMakeLists.txt on the following line: 

` TARGET_LINK_LIBRARIES( ${target} ${GLEW_LIBRARY} ${wxWidgets_LIBRARIES} wx_gtk2u_gl-3.0 libGL.so libz.so libGLU.so )`

instead of  `wx_gtk2u_gl-3.0` I knew that  `wx_gtk3u_gl-3.0` was available. But because it is within `ELSE(APPLE)`, I'm not entirely sure it is even needed. 

Hope it helps!

**Comment by arnaudbore** [comment]
Hi,

Fibernavigator is no longer developed and we highly encourage people to use another software such as [MI-Brain](https://imeka.ca/mi-brain/).

**Comment by ANG13** [comment]
Hello,

Thank you @arnaudbore for the info!

We'll have a look at that software.
